log:
  init:
    datefmt: '%d/%b/%y:%H:%M:%S %z'
    logfmt: '[%(asctime)s] [%(processName)s.%(threadName)s:%(levelname)s] %(message)s'
  logger:
    level: INFO
    handler: default.log
    logfmt: '[%(asctime)s] [%(filename)s line:%(lineno)d] [%(levelname)s] %(message)s'
